# Dokploy Configuration for Single Domain Setup
# This configuration sets up both frontend and backend behind a single domain
# with Next.js handling the API proxy

version: '3.8'

networks:
  household-planet:
    driver: bridge

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    networks:
      - household-planet
    environment:
      POSTGRES_DB: household_planet
      POSTGRES_USER: household_user
      POSTGRES_PASSWORD: your_secure_password_123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Service (Internal only)
  household-planet-backend:
    build:
      context: ./household-planet-backend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    networks:
      - household-planet
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://household_user:your_secure_password_123@postgres:5432/household_planet
      JWT_SECRET: ${JWT_SECRET:-household-planet-jwt-secret-key-2024-production-secure}
      JWT_EXPIRES_IN: 7d
      CORS_ORIGIN: https://householdplanet.co.ke
      BASE_URL: http://household-planet-backend:3001
      MPESA_BASE_URL: https://api.safaricom.co.ke
      MPESA_CALLBACK_URL: https://householdplanet.co.ke/api/payments/mpesa/callback
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - uploads_data:/app/uploads
    expose:
      - "3001"
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Service (Public facing)
  household-planet-frontend:
    build:
      context: ./household-planet-frontend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    networks:
      - household-planet
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://householdplanet.co.ke
      NEXT_PUBLIC_SITE_URL: https://householdplanet.co.ke
      NEXT_PUBLIC_ENVIRONMENT: production
    depends_on:
      - household-planet-backend
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.household-planet.rule=Host(`householdplanet.co.ke`)"
      - "traefik.http.routers.household-planet.tls=true"
      - "traefik.http.routers.household-planet.tls.certresolver=letsencrypt"
      - "traefik.http.services.household-planet.loadbalancer.server.port=3000"

volumes:
  postgres_data:
    driver: local
  uploads_data:
    driver: local