@echo off
echo Restarting backend with updated CORS configuration...
cd household-planet-backend
echo Installing dependencies...
npm install
echo Building backend...
npm run build
echo Starting backend...
npm run start:prod