export const BUSINESS_CONSTANTS = {
  INVENTORY: {
    LOW_STOCK_THRESHOLD: 10,
    OUT_OF_STOCK_THRESHOLD: 0,
    CRITICAL_STOCK_THRESHOLD: 5
  },
  
  PAGINATION: {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 20,
    MAX_LIMIT: 100,
    ADMIN_DEFAULT_LIMIT: 50
  },
  
  SEARCH: {
    MAX_QUERY_LENGTH: 100,
    AUTOCOMPLETE_LIMIT: 10,
    MAX_RESULTS: 100
  },
  
  ANALYTICS: {
    DEFAULT_PERIOD_DAYS: 30,
    WEEKLY_PERIOD_DAYS: 7,
    MONTHLY_PERIOD_MONTHS: 12,
    YEARLY_PERIOD_YEARS: 2
  },
  
  FILE_UPLOAD: {
    MAX_FILE_SIZE: 5 * 1024 * 1024, // 5MB
    IMAGE_MAX_WIDTH: 800,
    IMAGE_MAX_HEIGHT: 800,
    IMAGE_QUALITY: 85,
    BATCH_SIZE: 100,
    MAX_CSV_PRODUCTS: 1000
  },
  
  BUSINESS_LOGIC: {
    COST_MULTIPLIER: 0.6, // 60% cost assumption
    CUSTOMER_LIFETIME_MULTIPLIER: 3,
    DEFAULT_CUSTOMER_ACQUISITION_COST: 500,
    DEFAULT_RETURN_RATE: 2.5,
    DEFAULT_SESSION_TIME: 180
  }
};
