version: '3.8'

# Monitoring Stack for Household Planet Kenya
# Usage: docker-compose -f docker-compose.monitoring.yml up -d

networks:
  household-planet:
    external: true
  monitoring:
    driver: bridge

services:
  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: household-grafana
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - "3030:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=HouseholdPlanet2024!
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=https://householdplanetkenya.co.ke/grafana
    volumes:
      - grafana_data:/var/lib/grafana

  # Simple log viewer (lightweight alternative to full ELK stack)
  dozzle:
    image: amir20/dozzle:latest
    container_name: household-dozzle
    restart: unless-stopped
    networks:
      - household-planet
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DOZZLE_BASE: /logs

volumes:
  grafana_data:
    driver: local
